// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygxamuymjjpqhjoegweb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlneGFtdXltampwcWhqb2Vnd2ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NTQ2NjMsImV4cCI6MjA3NDIzMDY2M30.40fQwJ-v_X2xztJaAquLHVvMv3IcRWPYHYXuIIwkEnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});