// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjgsucleibzqvccjnlov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqZ3N1Y2xlaWJ6cXZjY2pubG92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MjQyMjMsImV4cCI6MjA2OTEwMDIyM30.pFkUziYl6ahGt_KmMccdWFhy6VCqoq_fN7NtEHGbF4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});